const DEMO={race:'名古屋 11R',safe_no:'5',safe_name:'サンライズジパング',long_no:'11',long_name:'サヴァ',jiyo_no:'2',jiyo_name:'テストホース',memo:'今日は前残り・内枠重視',safe_record:'184-96',long_record:'62-208',jiyo_record:'81-39',roi:'128%'};
const $=id=>document.getElementById(id);let client=null;
function fit(){const b=$('board');const s=Math.min(innerWidth/b.offsetWidth,innerHeight/b.offsetHeight)*.96;b.style.transform=`scale(${s})`}
function v(d,k){return d&&d[k]!==undefined&&d[k]!==null&&d[k]!==''?d[k]:DEMO[k]}
function betText(a,b,c){return{wide:`${a} - ${b} / ${c} - ${a}`,umaren:`${a} - ${b}`,sanren:`${c} - ${a} - ${b}`}}
function render(d){const safe=v(d,'safe_no'),long=v(d,'long_no'),jiyo=v(d,'jiyo_no');$('race').textContent=v(d,'race');$('safeNo').textContent=safe;$('safeName').textContent=v(d,'safe_name');$('longNo').textContent=long;$('longName').textContent=v(d,'long_name');$('jiyoNo').textContent=jiyo;$('jiyoName').textContent=v(d,'jiyo_name');$('memo').textContent=v(d,'memo');const bets=betText(safe,long,jiyo);$('wideBet').textContent=bets.wide;$('umarenBet').textContent=bets.umaren;$('sanrenBet').textContent=bets.sanren;$('records').textContent=`SAFE ${v(d,'safe_record')} / LONG ${v(d,'long_record')} / ジヨ ${v(d,'jiyo_record')} / ROI ${v(d,'roi')}`;$('updated').textContent='UPDATED '+new Date().toLocaleTimeString('ja-JP',{hour12:false});$('board').classList.remove('flash');void $('board').offsetWidth;$('board').classList.add('flash')}
function getUrl(){return window.DARKHORSE_SUPABASE_URL||window.SUPABASE_URL}function getKey(){return window.DARKHORSE_SUPABASE_ANON_KEY||window.SUPABASE_ANON_KEY}
async function load(){fit();if(!window.supabase||!getUrl()||!getKey()){render(DEMO);return}if(!client)client=window.supabase.createClient(getUrl(),getKey());const rowId=window.DARKHORSE_LIVE_ROW_ID||1;const {data,error}=await client.from('live_board').select('*').eq('id',rowId).single();if(error){console.warn(error.message);render(DEMO);return}render(data)}
function sub(){if(!client)return;const rowId=window.DARKHORSE_LIVE_ROW_ID||1;client.channel('whiteboard-live-'+rowId).on('postgres_changes',{event:'*',schema:'public',table:'live_board',filter:`id=eq.${rowId}`},p=>render(p.new||DEMO)).subscribe()}
addEventListener('resize',fit);addEventListener('load',async()=>{await load();sub();setInterval(load,3000)});
