const DEMO={race:'名古屋 11R',safe_no:'5',safe_name:'サンライズジパング',safe_star:'★★★★★',long_no:'11',long_name:'サヴァ',long_star:'★★★☆☆',jiyo_no:'2',jiyo_name:'テストホース',jiyo_star:'★★★★☆',memo:'今日は前残り・内枠重視',safe_record:'184-96',long_record:'62-208',jiyo_record:'81-39',roi:'128%',profit:'+214,580円',history:'○ ○ × ○ ○'};
const $=id=>document.getElementById(id);let client=null;
function fitStage(){const s=$('stage');const scale=Math.min(window.innerWidth/1920,window.innerHeight/1080);s.style.transform=`scale(${scale})`;s.style.left=`${(window.innerWidth-1720*scale)/2}px`;s.style.top=`${(window.innerHeight-960*scale)/2}px`}
function v(d,k){return d&&d[k]!==undefined&&d[k]!==null&&d[k]!==''?d[k]:DEMO[k]}
function makeBets(d){const a=v(d,'safe_no'),b=v(d,'long_no'),c=v(d,'jiyo_no');$('wideBet').textContent=`${a} - ${b} / ${c} - ${a}`;$('umarenBet').textContent=`${a} - ${b}`;$('sanrenBet').textContent=`${c} - ${a} - ${b}`}
function render(d){$('race').textContent=v(d,'race');$('safeNo').textContent=v(d,'safe_no');$('safeName').textContent=v(d,'safe_name');$('longNo').textContent=v(d,'long_no');$('longName').textContent=v(d,'long_name');$('jiyoNo').textContent=v(d,'jiyo_no');$('jiyoName').textContent=v(d,'jiyo_name');$('memo').textContent=v(d,'memo');$('safeRecord').textContent=v(d,'safe_record');$('longRecord').textContent=v(d,'long_record');$('jiyoRecord').textContent=v(d,'jiyo_record');$('roi').textContent=v(d,'roi');makeBets(d);$('updated').textContent='UPDATED '+new Date().toLocaleTimeString('ja-JP',{hour12:false});$('stage').classList.remove('flash');void $('stage').offsetWidth;$('stage').classList.add('flash')}
function getClient(){const url=window.DARKHORSE_SUPABASE_URL||window.SUPABASE_URL;const key=window.DARKHORSE_SUPABASE_ANON_KEY||window.SUPABASE_ANON_KEY;if(!window.supabase||!url||!key)return null;if(!client)client=window.supabase.createClient(url,key);return client}
async function fetchBoard(){const c=getClient();if(!c){render(DEMO);return}const rowId=window.DARKHORSE_LIVE_ROW_ID||1;const {data,error}=await c.from('live_board').select('*').eq('id',rowId).single();if(error){console.warn(error.message);render(DEMO);return}render(data)}
function subscribe(){const c=getClient();if(!c)return;const rowId=window.DARKHORSE_LIVE_ROW_ID||1;c.channel('whiteboard-live-'+rowId).on('postgres_changes',{event:'*',schema:'public',table:'live_board',filter:`id=eq.${rowId}`},p=>render(p.new||DEMO)).subscribe()}
window.addEventListener('resize',fitStage);window.addEventListener('load',async()=>{fitStage();await fetchBoard();subscribe();setInterval(fetchBoard,3000)});
